//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAPO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUESTO
    {
        public int PuestoId { get; set; }
        public string Funcion { get; set; }
        public Nullable<int> DepartamentoId { get; set; }
        public int Multiplicidad { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    }
}
