//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAPO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Nomina
    {
        public int NominaId { get; set; }
        public int FuncionId { get; set; }
        public string Funcion { get; set; }
        public string NombreCompleto { get; set; }
        public Nullable<decimal> Salario { get; set; }
        public string NombreDepartamento { get; set; }
        public Nullable<int> DepartamentoId { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Cedula { get; set; }
    }
}
